spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/f1_pool
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update  # Auto-création des tables en dev
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

logging:
  level:
    root: INFO
    com.ouimet: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'  # Tous les endpoints en dev
  endpoint:
    health:
      show-details: always

f1:
  fantasy:
    username: aouimet.dev@gmail.com
    password: DJX*jra*mjz8mqm@ana