spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/f1_pool
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  
  sql:
    init:
      mode: always
      data-locations: classpath:data-dev.sql
  jpa:
    hibernate:
      ddl-auto: create-drop  # Auto-création des tables en dev
    show-sql: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        '[format_sql]': true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

logging:
  level:
    root: INFO
    '[com.ouimet]': DEBUG
    '[org.hibernate.SQL]': DEBUG
    '[org.springframework.web]': DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'  # Tous les endpoints en dev
  endpoint:
    health:
      show-details: always
      